apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-balloon-web-config
  labels:
    app.kubernetes.io/name: {{ include "balloon-web.name" . }}
    helm.sh/chart: {{ include "balloon-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  config.json: "{}"     
