apiVersion: v1
data:
  balloon.conf: |
    log_format access  '$http_x_forwarded_for - $remote_user [$time_local] \"$request\" ' '$status $body_bytes_sent \"$http_referer\" ' '\"$http_user_agent\"';

    server {
        listen 80;
        access_log /dev/stdout;
        error_log /dev/stderr;
        client_max_body_size 1G;

        location ~ ^/(api|webdav|share) {
            index index.php;
            root /usr/share/balloon/bin/httpdocs;
            rewrite ^(.+)$ /index.php$1 last;
            break;
        }

        location ~ ^/index.php {
            root /usr/share/balloon/bin/httpdocs;
            fastcgi_pass {{ .Release.Name }}:{{ .Values.balloon.service.port }};
            fastcgi_read_timeout {{ .Values.nginx.fastcgi_read_timeout }};
            fastcgi_param SCRIPT_FILENAME /usr/share/balloon/bin/httpdocs$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_script_name;
            include /etc/nginx/fastcgi_params;
        }
    }
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-balloon-nginx-proxy
  labels:
    app.kubernetes.io/name: {{ include "balloon-proxy.name" . }}
    helm.sh/chart: {{ include "balloon-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
