apiVersion: v1
name: balloon-jobs
description: balloon jobs runner
type: application
version: 0.1.5
appVersion: 2.7.0-beta2
keywords:
- balloon
home: https://github.com/gyselroth/balloon
sources:
- https://github.com/gyselroth/balloon-helm
maintainers:
- name: Raffael Sahli
  email: sahli@gyselroth.com
