{{- if .Values.ingress.enabled -}}
{{- $fullName := include "balloon.fullname" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "balloon.name" . }}
    helm.sh/chart: {{ include "balloon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
{{- range .Values.ingress.hosts }}
{{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tls.secretName }}
{{- end }}
{{- end }}  
  rules:
  {{- range .Values.ingress.hosts }}    
    - host: {{ .name }}
      http:
        paths:
        {{- if index $.Values "balloon-web" "enabled" }}
        - path: "/"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        {{- end }}
        {{- if index $.Values "balloon-proxy" "enabled" }}
        - path: "/api"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        - path: "/openapi"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        - path: "/share"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        - path: "/wopi"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        - path: "/webdav"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        {{- end }}
        {{- if index $.Values "lool-collab" "enabled" }}
        - path: "/libreoffice"
          backend:
            serviceName: {{ $releaseName }}-lool-collab
            servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
