{{- if and .Values.ingress.enabled (index .Values "lool-collab" "enabled") -}}
{{- $fullName := include "balloon.fullname" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-libreoffice
  labels:
    app.kubernetes.io/name: {{ include "balloon.name" . }}
    helm.sh/chart: {{ include "balloon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: sticky-loolwsd
    nginx.ingress.kubernetes.io/session-cookie-path: /libreoffice
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
{{- range .Values.ingress.hosts }}
{{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tls.secretName }}
{{- end }}
{{- end }}  
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - path: "/libreoffice"
          backend:
            serviceName: {{ $fullName }}-lool-collab
            servicePort: http
  {{- end }}
{{- end }}
