apiVersion: v2
name: balloon
description: High performance, feature rich document management system written for the cloud
type: application
version: 0.2.12
appVersion: master
keywords:
- balloon
home: https://github.com/gyselroth/balloon
sources:
- https://github.com/gyselroth/balloon-helm
maintainers:
- name: Raffael Sahli
  email: sahli@gyselroth.com
