balloon-api:
  enabled: true
  
balloon-jobs:
  enabled: true
  
balloon-proxy:
  enabled: true
  
balloon-webui: 
  enabled: true

balloon-mongodb-metrics: 
  enabled: false

mongodb:
  enabled: true

elasticsearch:
  enabled: true

clamav: 
  enabled: true
  replicaCount: 2

libreoffice:
  enabled: true

browserless-chrome:
  enabled: true

lool-collab:
  enabled: true
  image:
    tag: 4.2.0.3
  collabora:
    server_name: '""'
    extra_params: --o:ssl.termination=true --o:ssl.enable=false --o:net.post_allow.host[0]=::ffff:10.[0-9]+.[0-9]+.[0-9]+ --o:storage.wopi.host[2]=::ffff:10.[0-9]+.[0-9]+.[0-9]+ --o:net.service_root="/libreoffice"
  livenessProbe:
    enabled: false
    initialDelaySeconds: 120
  readinessProbe:
    enabled: false

lool-convert:
  enabled: true
  image:
    tag: 4.2.0.3
  collabora:
    extra_params: --o:ssl.termination=false --o:ssl.enable=false --o:net.post_allow.host[0]=::ffff:10.[0-9]+.[0-9]+.[0-9]+ --o:storage.wopi.host[2]=::ffff:10.[0-9]+.[0-9]+.[0-9]+
  replicaCount: 2
  livenessProbe:
    initialDelaySeconds: 120

elasticsearch:
  enabled: true
  cluster:
    plugins:
    - ingest-attachment
