balloon-api:
  enabled: true
  
balloon-jobs:
  enabled: true
  
balloon-proxy:
  enabled: true

balloon-web: 
  enabled: true

balloon-mongodb-metrics: 
  enabled: false

mongodb:
  enabled: true

elasticsearch:
  enabled: true

clamav: 
  enabled: true
  kubeMeta:
    deploymentApiVersion: apps/v1

libreoffice:
  enabled: true

browserless-chrome:
  enabled: true

lool-collab:
  enabled: true
  image:
    tag: 4.2.0.3
  collabora:
    server_name: '""'
    extra_params: --o:ssl.termination=true --o:ssl.enable=false --o:net.post_allow.host[0]="::ffff:(10|172|192).[0-9]+.[0-9]+.[0-9]+" --o:storage.wopi.host[2]="::ffff:(10|172|192).[0-9]+.[0-9]+.[0-9]+" --o:net.service_root="/libreoffice"
  livenessProbe:
    path: /libreoffice/
    initialDelaySeconds: 120
  readinessProbe:
    path: /libreoffice/

lool-convert:
  enabled: true
  image:
    tag: 4.2.0.3
  collabora:
    extra_params: --o:ssl.termination=false --o:ssl.enable=false --o:net.post_allow.host[0]="::ffff:(10|172|192).[0-9]+.[0-9]+.[0-9]+" --o:storage.wopi.host[2]="::ffff:(10|172|192).[0-9]+.[0-9]+.[0-9]+"
  replicaCount: 1
  livenessProbe:
    initialDelaySeconds: 120

elasticsearch:
  enabled: true
  cluster:
    plugins:
    - ingest-attachment

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: 
  - name: "balloon.local"
    #tls:
      #secretName: secret-tls
