apiVersion: v1
kind: Service
metadata:
  name: {{ include "balloon-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "balloon-api.name" . }}
    helm.sh/chart: {{ include "balloon-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: php-fpm
      protocol: TCP
      name: php-fpm
  selector:
    app.kubernetes.io/name: {{ include "balloon-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
