apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "balloon-api.fullname" . }}-upgrade
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "balloon-api.fullname" . }}-upgrade
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"    
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-mongodb
        image: jwilder/dockerize
        command:
        - dockerize 
        - -timeout
        - 120s
        - -wait
        - http://{{ .Release.Name }}-elasticsearch-client:9200
        - -wait 
        - tcp://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb:27017
      containers:
      - name: balloon-api
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: 
        - balloon-apicli
        - upgrade
        - -vvvv
        env:
        - name: BALLOON_CLAMAV_URI
          value: tcp://{{ .Release.Name }}-clamav:3310
        - name: BALLOON_LIBREOFFICE_COLLAB_URL
          value: http://{{ .Release.Name }}-lool-collab:9980
        - name: BALLOON_LIBREOFFICE_CONVERT_URL
          value: http://{{ .Release.Name }}-lool-convert:9980
        - name: BALLOON_ELASTICSEARCH_URI
          value: http://{{ .Release.Name }}-elasticsearch-client:9200
        - name: BALLOON_MONGODB_URI
          value: mongodb://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-2.{{ .Release.Name }}-mongodb:27017
        - name: BALLOON_URL
          value: {{ .Values.url }}
        - name: BALLOON_BURL_BROWSERLESS_URL
          value: http://{{ .Release.Name }}-browserless-chrome:3000
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}          
  backoffLimit: 4
