apiVersion: v2
name: balloon-mongodb-metrics
description: Provides overall balloon metrics using data from MongoDB
type: application
version: 0.0.3
appVersion: 1.0.0-beta2
keywords:
- balloon
home: https://github.com/gyselroth/balloon
sources:
- https://github.com/gyselroth/balloon-helm
maintainers:
- name: Raffael Sahli
  email: sahli@gyselroth.com
